name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Compilar:
  #criar maquina virtual no pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Fazer o guit clone
      uses: actions/checkout@v4

    - name: Executando primeiro comando
      run: echo "amo DEVOPS:)"

    - name: Executando um ou mias comandos 
      run: |
          ls -l
          echo "fim do processo"
          
